os: linux # => 1
language: python # => 2

python: # => 3
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
env: # => 5
  - DJANGO=3.1.6  DB=sqlite
  
install: # => 6
  - pip install django
  - pip install django-crispy-forms
  
script: # => 7
  - python Tweeter/manage.py test
