# Generated by Django 3.1.1 on 2021-03-10 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Django migration stuff
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20210226_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(related_name='Followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='Following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
